  Api::Space.create(name: 'Eiffel Tower', price: 1250, location: "Paris", size: 850, property_type: "Tower")
  Api::Space.create(name: 'The White House', price: 1950, location: "Washington D.C.", size: 650, property_type: "Mansion")
  Api::Space.create(name: 'Houses of Parliament', price: 1800, location: "London", size: 600, property_type: "Old Buildings")
  Api::Space.create(name: 'Burj Al Arab', price: 5000, location: "Dubai", size: 1000, property_type: "Hotel")
  Api::Space.create(name: 'Pyramids of Giza', price: 8000, location: "Cairo", size: 35000, property_type: "Pyramids")
  Api::Space.create(name: 'Colosseum', price: 6000, location: "Rome", size: 900, property_type: "Arena")
  Api::Space.create(name: 'Old Trafford', price: 1000, location: "Manchester", size: 500, property_type: "Stadium")
  Api::Space.create(name: 'Makers Academy', price: 8000, location: "London", size: 350, property_type: "Offices")
  Api::Space.create(name: 'Canary Wharf', price: 1800, location: "London", size: 500, property_type: "Offices")
  Api::Space.create(name: 'Buckingham Palace', price: 1200, location: "London", size: 700, property_type: "Palace")